services:
  python-api:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    links:
      - node-app
    # Add features here
    environment:
      - DEVCONTAINER_FEATURES=github.com/devcontainers/features/python

  node-app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    # Add features here
    environment:
      - DEVCONTAINER_FEATURES=github.com/devcontainers/features/node
